# Generated by Django 4.0.5 on 2022-07-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMagaz', '0003_purchase_purchasereturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='time',
        ),
    ]
