# Generated by Django 4.0.5 on 2022-07-02 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myMagaz', '0004_remove_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
