# Generated by Django 4.0.5 on 2022-07-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMagaz', '0005_purchase_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='time',
        ),
    ]
