# Generated by Django 4.0.5 on 2022-07-02 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myMagaz', '0006_remove_purchasereturn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
