# Generated by Django 4.0.5 on 2022-07-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myMagaz', '0007_purchasereturn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myMagaz.purchase'),
        ),
    ]
